[package]
name = "wave-function-collapse"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.44", features = ["derive"] }
colored = "3.0.0"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
